FROM nnurphy/jpl:rust

### Haskell
ENV STACK_ROOT=/opt/stack \
    STACKAGE_VERSION=lts-13.28

RUN set -ex \
  ; mkdir -p ${STACK_ROOT} && mkdir -p ${HOME}/.cabal \
  ; curl -sSL https://get.haskellstack.org/ | sh \
  ; stack config set system-ghc --global false && stack config set install-ghc --global true  \
  ; stack update && stack setup \
  ; git clone https://github.com/gibiansky/IHaskell \
  ; cd IHaskell \
  # pip: 去掉版本号,尽量使用已安装版本
  ; sed -i 's/==.*$//g' requirements.txt \
  ; pip --no-cache-dir install -r requirements.txt \
  ; sed -i "s/^\(resolver:\).*$/\1 ${STACKAGE_VERSION}/g" stack.yaml \
   # parsers boomerang criterion weigh arithmoi syb multipart HTTP html xhtml
  ; stack install \
      hlint hindent highlight ghcid clock hashtables dlist binary store megaparsec Earley \
      optparse-applicative shelly aeson yaml taggy cassava JuicyPixels diagrams \
      persistent mwc-random shake TCache MonadRandom monad-logger monad-journal \
      pipes conduit machines mustache cryptonite http-conduit wreq servant scotty wai \
      websockets warp smallcheck hspec extensible-exceptions deepseq \
      filepath directory hpc pretty process hmatrix linear ad integration statistics \
      monad-par async stm classy-prelude reactive-banana uniplate singletons dimensional \
      free extensible-effects freer bound unbound-generics ghc-prim primitive memory array \
      bytestring containers template-haskell time transformers unix alex attoparsec fgl mtl \
      network QuickCheck parallel random call-stack regex-base regex-compat regex-posix \
      text hashable unordered-containers vector zlib fixed \
      transformers-compat network-uri flow lens \
  # Disabled for now because gtk2hs-buildtools doesn't work with lts-13 yet
  #; stack install gtk2hs-buildtools \
  ; stack install --fast \
  ; ${HOME}/.local/bin/ihaskell install --stack \
  ; mkdir -p ${STACK_ROOT}/global-project \
  # 设置全局 stack resolver, 避免运行时重新安装 lts
  ; sed -i "s/^\(resolver:\).*$/\1 ${STACKAGE_VERSION}/g" ${STACK_ROOT}/global-project/stack.yaml \
  ; rm -rf ${STACK_ROOT}/programs/x86_64-linux/*.tar.xz \
  ; rm -rf ${STACK_ROOT}/pantry/hackage/* \
  ; rm -rf ${HOME}/IHaskell/ \
  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

COPY .ghci ${HOME}/.ghci

RUN set -ex \
  # ; jupyter labextension install ihaskell_labextension \
  ; jupyter labextension install jupyterlab-ihaskell \
  ; rm -rf /usr/local/share/.cache/yarn
